import { Lightbulb, TrendingUp, AlertCircle, CheckCircle } from 'lucide-react';
import Card from '../ui/Card';

interface AIInsightsProps {
  insights: string;
  suggestions: string[];
  consistencyScore: number;
  consistencyGrade: string;
}

export default function AIInsights({ insights, suggestions, consistencyScore, consistencyGrade }: AIInsightsProps) {
  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-500';
    if (score >= 60) return 'text-yellow-500';
    return 'text-red-500';
  };

  const getGradeColor = (grade: string) => {
    if (grade === 'A' || grade === 'B') return 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400';
    if (grade === 'C') return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400';
    return 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400';
  };

  return (
    <div className="space-y-4">
      {/* Consistency Score Card */}
      <Card className="border-l-4 border-l-github-accent-emphasis">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-github-accent/20 rounded-lg flex items-center justify-center">
              <TrendingUp className="w-5 h-5 text-github-accent-emphasis" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-github-text">Consistency Score</h3>
              <p className="text-sm text-github-text-secondary">How consistent is your development?</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <div className={`text-4xl font-bold ${getScoreColor(consistencyScore)}`}>
              {consistencyScore}
            </div>
            <div className={`px-3 py-1 rounded-full text-sm font-semibold ${getGradeColor(consistencyGrade)}`}>
              Grade {consistencyGrade}
            </div>
          </div>
        </div>
        <div className="w-full bg-github-border rounded-full h-3 overflow-hidden">
          <div
            className={`h-full transition-all duration-500 ${
              consistencyScore >= 80
                ? 'bg-green-500'
                : consistencyScore >= 60
                ? 'bg-yellow-500'
                : 'bg-red-500'
            }`}
            style={{ width: `${consistencyScore}%` }}
          />
        </div>
      </Card>

      {/* AI Insights Card */}
      <Card className="border-l-4 border-l-purple-500">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 bg-purple-100 dark:bg-purple-900/30 rounded-lg flex items-center justify-center flex-shrink-0">
            <Lightbulb className="w-5 h-5 text-purple-600 dark:text-purple-400" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-github-text mb-2">AI-Powered Insights</h3>
            <p className="text-github-text-secondary leading-relaxed">{insights}</p>
          </div>
        </div>
      </Card>

      {/* Suggestions Card */}
      {suggestions && suggestions.length > 0 && (
        <Card>
          <div className="flex items-start gap-3 mb-4">
            <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-lg flex items-center justify-center flex-shrink-0">
              <CheckCircle className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-github-text">Improvement Suggestions</h3>
              <p className="text-sm text-github-text-secondary">Ways to improve your commit consistency</p>
            </div>
          </div>
          <ul className="space-y-2">
            {suggestions.map((suggestion, index) => (
              <li key={index} className="flex items-start gap-2 text-github-text-secondary">
                <span className="text-github-accent-emphasis mt-1">•</span>
                <span>{suggestion}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Info Card */}
      <Card className="bg-github-accent/5 border-github-accent">
        <div className="flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-github-accent-emphasis flex-shrink-0 mt-0.5" />
          <div className="text-sm text-github-text-secondary">
            <p className="font-medium text-github-text mb-1">About AI Insights</p>
            <p>
              These insights are generated by Google Gemini AI based on your commit patterns. 
              They analyze your work behavior, time gaps, and commit distribution to help you 
              develop better coding habits.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
